services:
  mysql:
    image: mysql:8.4
    container_name: gymtrack-mysql

    environment:
      MYSQL_DATABASE: gymtrack_db
      MYSQL_USER: gymtrack
      MYSQL_PASSWORD: gymtrack123
      MYSQL_ROOT_PASSWORD: root123

    ports:
      - "3306:3306"

    volumes:
      - gymtrack_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: gymtrack-phpmyadmin

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    ports:
      - "8081:80"

    depends_on:
      - mysql

volumes:
  gymtrack_mysql_data:
