spring.application.name=gymtrack-backend

# Base de datos
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto (opcional en Spring Boot 3, pero no mole sta)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect